from . import res_company
from . import res_config_settings
from . import product_category
from . import product_template
from . import revenue_recognition_line
from . import account_move_line
from . import stock_move
from . import sale_order_line
from . import sale_order
from . import stock_picking
from . import account_move
